
export const cards =
[
    {
        name: 'Donald Trump',
        ability: 'Build Wall',
        health: 950,
        defence: 390,
        mana: 7,
        speed: 70,
        attack: 130,
        specialAttack: 140,
    },
    {
        name: 'Electro',
        ability: 'Electro Charge',
        health: 900,
        defence: 200,
        mana: 7,
        speed: 110,
        attack: 120,
        specialAttack: 270,
    },
    {
        name: 'Hammer Head',
        ability: 'Big Hammer',
        health: 900,
        defence: 200,
        mana: 5,
        speed: 60,
        attack: 120,
        specialAttack: 220,
    },
    {
        name: 'Sea Horse',
        ability: 'Current Ride',
        health: 850,
        defence: 200,
        mana: 7,
        speed: 110,
        attack: 120,
        specialAttack: 230,
    },
    {
        name: 'Spy Hippo',
        ability: 'Poo Fling',
        health: 990,
        defence: 330,
        mana: 4,
        speed: 60,
        attack: 110,
        specialAttack: 210,
    },
    {
        name: 'Extreme chesse',
        ability: 'Obeast Burger',
        health: 950,
        defence: 210,
        mana: 6,
        speed: 80,
        attack: 130,
        specialAttack: 240,
    },
    {
        name: 'Hippocampus',
        ability: 'Whirlpool',
        health: 850,
        defence: 250,
        mana: 7,
        speed: 100,
        attack: 110,
        specialAttack: 210,
    },
    {
        name: 'Trumps Henchmen',
        ability: 'Protect trump',
        health: 940,
        defence: 380,
        mana: 8,
        speed: 100,
        attack: 115,
        specialAttack: 220,
    },
    {
        name: 'Sharperz',
        ability: 'Step on Shapes',
        health: 950,
        defence: 400,
        mana: 7,
        speed: 80,
        attack: 90,
        specialAttack: 180,
    },
    {
        name: 'Just Some Stuff in a Suit',
        ability: 'I\'m throwing stuff at you',
        health: 0,
        defence: 0,
        mana: 0,
        speed: 0,
        attack: 0,
        specialAttack: 0,
    },
    {
        name: 'alien UFO',
        ability: 'abduction',
        health: 910,
        defence: 350,
        mana: 8,
        speed: 130,
        attack: 100,
        specialAttack: 200,
    },
    {
        name: 'spwash',
        ability: '??',
        health: 1000,
        defence: 390,
        mana: 8,
        speed: 60,
        attack: 100,
        specialAttack: 190,
    },
    {
        name: 'Lava Monster',
        ability: 'Volcano strick',
        health: 990,
        defence: 300,
        mana: 8,
        speed: 55,
        attack: 140,
        specialAttack: 260,
    },
    {
        name: 'spy rino',
        ability: 'Give em da horn',
        health: 920,
        defence: 900,
        mana: 6,
        speed: 70,
        attack: 135,
        specialAttack: 250,
    },
    {
        name: 'spy pig ionk ionk',
        ability: '??',
        health: 950,
        defence: 350,
        mana: 6,
        speed: 100,
        attack: 110,
        specialAttack: 200,
    },
]
